
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      /*
      apiKey: 'AIzaSyDjWjuCwnIyNFkH1K5Kfy1DAbn_jkyXssw',
    appId: '1:248317208047:web:7a5ec6b32c11b8fd37821a',
    messagingSenderId: '248317208047',
    projectId: 'hitch-e4a25',
    authDomain: 'hitch-e4a25.firebaseapp.com',
    storageBucket: 'hitch-e4a25.appspot.com',
    measurementId: 'G-6Z28FCR9Y1',
*/
      apiKey: "AIzaSyBE8jYhnpmyeP48zBNhVGYgYugKeyan5GE",
      authDomain: "myprojectdatabase-774bf.firebaseapp.com",
      databaseURL: "https://myprojectdatabase-774bf-default-rtdb.europe-west1.firebasedatabase.app",
      projectId: "myprojectdatabase-774bf",
      storageBucket: "myprojectdatabase-774bf.firebasestorage.app",
      messagingSenderId: "624943639997",
      appId: "1:624943639997:web:fe783117ca33db0b9376d4"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDypM3uyKBb4AcfRVK92WOoyx7dgyyAqHc',
    appId: '1:624943639997:android:4067da0f44a5de959376d4',
    messagingSenderId: '624943639997',
    projectId: 'myprojectdatabase-774bf',
    storageBucket: 'myprojectdatabase-774bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByPJBCEcTCp0EQcGCHXY1Wz8I1mhRAaLI',
    appId: '1:248317208047:ios:c73205c7c000c1ac37821a',
    messagingSenderId: '248317208047',
    projectId: 'hitch-e4a25',
    storageBucket: 'hitch-e4a25.appspot.com',
    iosClientId: '248317208047-mjhism759kathie80lapuh2074cavm2o.apps.googleusercontent.com',
    iosBundleId: 'com.example.hitchApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByPJBCEcTCp0EQcGCHXY1Wz8I1mhRAaLI',
    appId: '1:248317208047:ios:c73205c7c000c1ac37821a',
    messagingSenderId: '248317208047',
    projectId: 'hitch-e4a25',
    storageBucket: 'hitch-e4a25.appspot.com',
    iosClientId: '248317208047-mjhism759kathie80lapuh2074cavm2o.apps.googleusercontent.com',
    iosBundleId: 'com.example.hitchApp',
  );
}
